EN_descriptions = { # list of English descriptions for many concepts. Words surrounded by && represent other objects with their own descriptions, which are listed after the second & sign
    "federal_presidential_consitiutional_republic" : "The government of the United States can be described as a Federal Presidential Constitutional Republic; that is, power is shared in a &federal system&federal_system, a &president&president serves as the head of state, laws for the government are given in the &Constitution&constitution, and political power is conferred through &public representatives&congress.",
    "federal_system" : "The federal system describes the seperation of powers within a nation between 'levels' of government. In the United States, soverignty is shared between the Federal, State, and Local levels of government.",
    "state" : "A state (or commonwealth) is one of 50 such political entities within the United States of America. Each state has jurisdiction over a set geographic area and sets many of their own laws and policies.",
    "party" : "Though not described in the &Constitution&constitution, political parties have come to hold tremendous political power in the United States. Political parties are formed by like-minded &political constituents&voters to represent at-large a given &ideology&ideology and/or &political goal&issue.",
    "convention" : "The convention process is designed to determine which &candidates&candidate are most apt to represent their &political parties&party in the &general election&general_election.",
    "primary" : "Primary elections are a part of the &candidate-selection system&convention. A popular vote amongst the &voting public&voters determines the preferred candidate through secret ballots. &Delegates&delegate are awarded to favored candidates.",
    "closed primary" : "A closed primary is a &primary&primary in which only voters registered with a particular &party&party may participate. In some cases, &independent voters&independent are allowed to participate.",
    "semi-closed primary" : "A semi-closed or open partisan primary is a &primary&primary in which &unaffiliated&independent voters may vote for either party, but cross-party voting is prohibited.",
    "open primary" : "An open primary is a &primary&primary in which voters may vote for any one candidate of their choice. In some cases, cross-voters may be required to declare their choice publically.",
    "caucus" : "Caucuses are a part of the &candidate-selection system&convention. Participants often debate about the candidates and publically declare their preferred candidate. %Delegates&delegate are awarded to favored candidates.",
    "delegate" : "Delegates are people who represent their &state&state at a &party's&party &nomination convention&convention. Delegates are selected by the results of a &primary&primary or &caucus&caucus, or may be given the position in recognition of their party leadership.",
    "front-loading" : "&States&state often attempt to 'front-load' their %primaries%primary or &caucuses&caucus by pushing them as early as possible in the year. This is done to attempt to gain influence in the course of the election and on party decisions. &Parties&party combat this by offering &delegate&delegate-count incentives for later dates.",
    "bloc" : "A voting bloc is a group of &voters&voters distinguised by a &demographic trait&demographic or by a preference on a given &political issue&issue. Candidates often focus on gaining support of a bloc rather than focusing on individual voters, simplifying the &campaign process&campaign.",
    "demographic" : "A demographic is a grouped sector of a population with some common inherent feature like &age&generation, &race or ethnicity&race_ethnicity, &religion&religion, etc. &Demographic blocs&bloc are often used to analyze trends in population data.",
    "generation" : "A common &demographic classification&demographic has to do with age. People born around a certain time (usually about 20-30 years apart) are assigned to a Generational Cohort. People in different generations are likely to have had a different experience of childhood and adulthood.",
    "race_ethnicity" : "A common &demographic classification&demographic has to do with race or ethnicity. Since the 17th century, 'race' has been used to group persons with a kinship relation into one bloc. Ethnicity has to do with common nations of origin, ancestry, tradition, etc. The usage of these blocs in analytics can be controversial, but can in some cases give insight into population trends.",
    "religion" : "Religion describes a societal-cultural system of belief, morality, worldview, and faith relating humanity to percieved supernatural or spiritual elements of the observable world.",
    "family_status" : "Family status describes the general condiditon of one's home life. Namedly, one being single or married can evidence a great difference in one's day-to-day life, as can the number of children in a household.",
    "education" : "Education describes the maximum academic achievement of an individual. In the United States, formal education is divided into pre-primary (nursery schools and Kindergartens), elementary grades (primary school), middle or junior-high grade school, high or senior-high school, tertiary / undergraduate education, masters or professional studies, and doctoral studies.",
    "employment" : "Employment is an important factor of the lives of many Americans. As a demographic bloc, employment is used to distinguish between industries or classes of work.",
    "residency" : "Residency is a term used to describe the conditions of one's home location and surrounding geography. Residents of urban areas live within densely-populated areas like cities. Residents of sub-urban areas live in somewhat less dense areas, though there are often major commercial areas within suburbs. Residents of rural areas live outside towns or cities marked by low population density.",
    "voter" : "A voter is a constituent of the United States government who may legally participate in local, state, and federal elections. Nearly all registered US citizens over the age of 18 are allowed to vote, about 75%\ of the total population. Because all other people are non-voters, political candidates often have little reason to appeal to constituents who are not a part of this bloc.",
    "constitution" : "The Constitution is the &supreme law&law of the United States. It outlines such government systems as the &Federal System&federal_system, &Separation of Powers&separation_of_powers, and the broad political processes and duties of government offices. The Consitution was ratified in 1787, and is considered the most important political document in the United States.",
    "bill_of_rights" : "The Bill of Rights is a collective name for the first ten &Amendments&amendments to the &Constitution&constitution. The early Anti-Federalist party ensured that the document establishes clear limitations on government power and guarantees of personal rights and freedoms.",
    "amendments" : "Amendments to the &Constitution&constitution are changes which serve to clarify definitions, add rights and liberties, change processes, and prohibit certain actions. Amendments are proposed by &Congress&congress and ratified by the &State Governments&.",
    "law" : "The law consists of regulations and codes for residents of the USA, &levels of government&federal_system, and &judicial processes&court related to certain actions, processes, and rights. The %Constitution&constitution and &Bill of Rights&bill_of_rights ensure that State laws take precedence over Federal ones.",
    "policy" : "",
    "executive_order" : "An executive order is a directive issued by the &President&president.",
    "president" : "The president of the United States is the Cheif Executive Officer of the nation.",
    "election" : "Elections are the primary way that &common voters&voters influence the government. At each &level of government&federal_system, citizens make their preferences known through popular elections.",
    "local_government" : "",
    "congress" : "",
    "senate" : "",
    "house_of_representatives" : "",
    "supreme_court" : "",
    "separation_of_powers" : "",
    "executive" : "",
    "legislative" : "",
    "judicial" : "",
    "court" : ""
}
