EN_system_text { # list of English text which will be displayed by the game for titles and labels etc
    "title" : "Race for the Presidency",
    "newsave_text" : "New Game",
    "opensave_text" : "Continue Game",
    "settings_text" : "Settings",
    "open_game_text" : "Load Save",
    "closegame_text" : "Close Game",
    "return_to_desktop_text" : "Return to Desktop",
    "return_to_desktop_prompt_text" : "Return to Desktop?",
    "return_to_menu_text" : "Return to Menu",
    "return_to_menu_prompt_text" : "Return to Menu?",
    "savegame_text" : "Save Game",
    "delete_save_text" : "Delete Save",
    "delete_save_prompt_text" : "Delete this Save?",
    "candidate" : "Candidate",
    "delegate" : "Delegate",
    "party_member" : "Party Member",
    "party_leader" : "Party Leader",
    "president" : "President",
    "vice_president" : "Vice President",
    "running_mate" : "Running Mate",
    "representative" : "Representative",
    "senator" : "Senator",
    "congressman" : "Congressman",
    "congresswoman" : "Congresswoman",
    "congressperson" : "Congressperson",
    "speaker_hor" : "Speaker of the House"
    "president_pro_tempore" : "President pro tempore",
    "supreme_court" : "Supreme Court",
    "sc_justice" : "Supreme Court Justice",
    "sc_cheif_justice" : "Cheif Justice",
    "governonr" : "Governor",
    "state_representative" : "State Representative",
    "united_states" : "United States",
    "united_states_of_america" : "United States of America",
    "us_abbreviation" : "US",
    "usa_abbreviation" : "USA",
    "january" : "January",
    "jan_abbreviation" : "JAN",
    "february" : "February",
    "feb_abbreviation" : "FEB",
    "march" : "March",
    "mar_abbreviation" : "MAR",
    "april" : "April",
    "apr_abbreviation" : "APR",
    "may" : "May",
    "may_abbreviation" : "MAY",
    "june" : "June",
    "jun_abbreviation" : "JUN",
    "july" : "July",
    "jul_abbreviation" : "JUL",
    "august" : "August",
    "aug_abbreviation" : "AUG",
    "september" : "September",
    "sep_abbreviation" : "SEP",
    "october" : "October",
    "oct_abbreviation" : "OCT",
    "november" : "November",
    "nov_abbreviation" : "NOV",
    "december" : "December",
    "dec_abbreviation" : "DEC"
}
